# Using container-based infrastructure
dist: trusty
sudo: false

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src

# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            - libncurses5-dev
            - texinfo
            - help2man
            - g++

install:
    # Building crosstool-NG core
    - ./ct-ng-install.sh

    

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    - CT_SAMPLE=aarch64-unknown-linux-gnueabi


# Building the standard samples
script:
    # Build the toolchain


    # put it into docker environment
    #- . ./.travis.sh      # Load the travis environment
    - ct-ng $CT_SAMPLE    # Configure the build
    #- ct-ng_travis_build  # Build the sample

# On failure displaying the last lines of the log file
after_failure:
    - tail -n 1000 build.log
