# forced to use Sudo Enabled infrastructure for building docker image
sudo: required

services:
  - docker

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src

# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            - libncurses5-dev
            - texinfo
            - help2man
            - g++

install:
    # install crosstool-NG
    - wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.23.0.tar.xz
    - mkdir crosstool-ng 
    - tar -xf crosstool-ng-*.tar* -C crosstool-ng --strip-components=1 
    - cd crosstool-ng
    - ./configure --enable-local
    - make

env:
    - TOOLCHAIN=aarch64-unknown-linux-gnueabi

script:
    # Build the toolchain
    - ct-ng git@github.com:smallzzy/metwo-dev.git
    - ct-ng $TOOLCHAIN    # Configure the build
    - ct-ng build.8

    # put it into docker environment
    #- . ./.travis.sh      # Load the travis environment
    #- ct-ng_travis_build  # Build the sample

# On failure displaying the last lines of the log file
after_failure:
    - tail -n 1000 build.log
