version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    
    # only build the master branch
    branches:
      only:
        - master
  
    # build step
    working_directory: ~/metwo_dev

    steps:
      - checkout

      - run:
          name: install dependency
          command: |
            sudo apt-get install -y gawk gcc gperf bison flex texinfo help2man make libncurses5-dev python-dev
    
      - run: 
          name: build ct-ng core                              
          command: |
            wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.23.0.tar.xz
            mkdir crosstool-ng 
            tar -xf crosstool-ng-*.tar* -C crosstool-ng --strip-components=1 
            cd crosstool-ng
            ./configure --prefix=$HOME/ct_build
            make && make install
      
      - restore_cache:
          keys:
            - src-package-1.23.0

      - run:
          name: build toolchain
          environment:
            TOOLCHAIN: "aarch64-unknown-linux-gnueabi"
          command: |
            export PATH=$PATH:$HOME/ct_build/bin
            . ./build.sh
            mkdir -p $HOME/src
            mkdir toolchain_build && cd toolchain_build
            ct-ng $TOOLCHAIN
            ct-ng_override && ct-ng_build
      
      - save_cache:
          key: src-package-1.23.0
          paths: 
            - $HOME/src
      
      # build docker image